language: generic

services:
  - docker

# after_success:
#   - docker build -t sergi-s/cloud-project .

#   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#   - docker push sergi-s/cloud-project

deploy:
  provider: elasticbeanstalk
  region: eu-east-2
  app: my-cloud-project
  env: Mycloudproject-env
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: multi-container-cloud-project
  bucket_path: "docker"
  on:
    branch: main